'use client'

import { SOAPNote as SOAPNoteType } from '@/lib/supabase'
import { FileText, Download } from 'lucide-react'

interface SOAPNoteProps {
  soapNote: SOAPNoteType
  petName: string
  sessionName: string
}

export default function SOAPNote({ soapNote, petName, sessionName }: SOAPNoteProps) {
  const handleDownload = () => {
    const content = `
SOAP NOTE - ${sessionName}
Pet: ${petName}
Date: ${new Date().toLocaleDateString()}

SUBJECTIVE:
${soapNote.subjective}

OBJECTIVE:
${soapNote.objective}

ASSESSMENT:
${soapNote.assessment}

PLAN:
${soapNote.plan}

SEVERITY: ${soapNote.severity.toUpperCase()}

---
Generated by Luni Triage AI
    `.trim()

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${sessionName}-SOAP-Note.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'low': return 'text-green-800 bg-green-100'
      case 'medium': return 'text-yellow-800 bg-yellow-100'
      case 'high': return 'text-red-800 bg-red-100'
      case 'urgent': return 'text-red-900 bg-red-200 font-bold'
      default: return 'text-gray-800 bg-gray-100'
    }
  }

  return (
    <div className="bg-white rounded-lg border border-gray-200 p-6">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center">
          <FileText className="w-5 h-5 text-primary-600 mr-2" />
          <h3 className="text-lg font-semibold text-gray-900">SOAP Note</h3>
        </div>
        <div className="flex items-center space-x-2">
          <span className={`px-2 py-1 rounded-full text-xs font-medium ${getSeverityColor(soapNote.severity)}`}>
            {soapNote.severity.toUpperCase()}
          </span>
          <button
            onClick={handleDownload}
            className="flex items-center px-3 py-1 text-sm text-primary-600 hover:text-primary-700 border border-primary-200 hover:border-primary-300 rounded-md transition-colors"
          >
            <Download className="w-4 h-4 mr-1" />
            Download
          </button>
        </div>
      </div>

      <div className="space-y-4">
        <div>
          <h4 className="font-semibold text-gray-900 mb-2">Subjective</h4>
          <p className="text-gray-700 text-sm leading-relaxed">{soapNote.subjective}</p>
        </div>

        <div>
          <h4 className="font-semibold text-gray-900 mb-2">Objective</h4>
          <p className="text-gray-700 text-sm leading-relaxed">{soapNote.objective}</p>
        </div>

        <div>
          <h4 className="font-semibold text-gray-900 mb-2">Assessment</h4>
          <p className="text-gray-700 text-sm leading-relaxed">{soapNote.assessment}</p>
        </div>

        <div>
          <h4 className="font-semibold text-gray-900 mb-2">Plan</h4>
          <p className="text-gray-700 text-sm leading-relaxed">{soapNote.plan}</p>
        </div>
      </div>

      <div className="mt-6 pt-4 border-t border-gray-200">
        <p className="text-xs text-gray-500">
          This SOAP note is AI-generated and should be reviewed by a veterinary professional.
        </p>
      </div>
    </div>
  )
}